"""Magnific external orchestration and local result-ingestion bridge."""

from .bridge import (
    MAGNIFIC_ADAPTER_VERSION,
    MAGNIFIC_ASPECT_RATIO_VOCABULARY_VERSION,
    MAGNIFIC_CONFIG_VERSION,
    MAGNIFIC_EXECUTION_SURFACE,
    MAGNIFIC_MODEL_ASPECT_RATIOS,
    MAGNIFIC_MODEL_CAPABILITY_SNAPSHOTS,
    MAGNIFIC_MODEL_SNAPSHOT_VERSION,
    MAGNIFIC_PROVIDER_ID,
    MAGNIFIC_RESULT_SCHEMA,
    MAGNIFIC_SUPPORTED_ASPECT_RATIOS,
    MagnificExecutionBinding,
    MagnificJobSpec,
    MagnificModelCapabilitySnapshot,
    MagnificProvider,
    MagnificReferenceBinding,
    MagnificResultManifest,
    get_magnific_model_snapshot,
    map_magnific_aspect_ratio,
)

__all__ = [
    "MAGNIFIC_ADAPTER_VERSION",
    "MAGNIFIC_ASPECT_RATIO_VOCABULARY_VERSION",
    "MAGNIFIC_CONFIG_VERSION",
    "MAGNIFIC_EXECUTION_SURFACE",
    "MAGNIFIC_MODEL_ASPECT_RATIOS",
    "MAGNIFIC_MODEL_CAPABILITY_SNAPSHOTS",
    "MAGNIFIC_MODEL_SNAPSHOT_VERSION",
    "MAGNIFIC_PROVIDER_ID",
    "MAGNIFIC_RESULT_SCHEMA",
    "MAGNIFIC_SUPPORTED_ASPECT_RATIOS",
    "MagnificExecutionBinding",
    "MagnificJobSpec",
    "MagnificModelCapabilitySnapshot",
    "MagnificProvider",
    "MagnificReferenceBinding",
    "MagnificResultManifest",
    "get_magnific_model_snapshot",
    "map_magnific_aspect_ratio",
]
