"""PAG-M07 deterministic structural quality and diversity layer."""

from .core import (
    DiversityReport,
    DuplicatePair,
    GridInput,
    GRID_HASH_SCHEMA,
    GRID_HASH_VERSION,
    NegativeSpaceEvidence,
    QualityAnalysis,
    QualityCode,
    QualityInputError,
    QualityMetrics,
    QualityPolicy,
    QualityReport,
    SimilarityMetrics,
    analyze_grid,
    canonical_grid_bytes,
    compare_grids,
    diversity_report,
    evaluate_grid,
    exact_duplicate_groups,
    logical_grid_hash,
)
from .review import ReviewEntry, build_contact_sheet, build_review_manifest, write_review_pack

__all__ = [
    "DiversityReport",
    "DuplicatePair",
    "GridInput",
    "GRID_HASH_SCHEMA",
    "GRID_HASH_VERSION",
    "NegativeSpaceEvidence",
    "QualityAnalysis",
    "QualityCode",
    "QualityInputError",
    "QualityMetrics",
    "QualityPolicy",
    "QualityReport",
    "ReviewEntry",
    "SimilarityMetrics",
    "analyze_grid",
    "build_contact_sheet",
    "build_review_manifest",
    "canonical_grid_bytes",
    "compare_grids",
    "diversity_report",
    "evaluate_grid",
    "exact_duplicate_groups",
    "logical_grid_hash",
    "write_review_pack",
]
