"""Generator-independent SCRUBBOTS contract APIs for M01."""

from .color_usage import (
    ColorUsageContractError,
    actual_used_palette_ids,
    count_used_colors,
    resolve_palette_subset,
    select_palette_subset,
    validate_used_color_count,
    validate_palette_subset,
)
from .difficulty import (
    CURRENT_DIMENSION_SCHEMA_VERSION,
    Difficulty,
    DimensionBand,
    DimensionContractError,
    dimension_band,
    is_legal_dimensions,
    LEGACY_DIMENSION_SCHEMA_VERSION,
    parse_difficulty,
    resolve_dimensions,
    select_dimensions,
    SUPPORTED_DIMENSION_SCHEMA_VERSIONS,
    validate_dimensions,
    validate_height,
    validate_width,
)
from .dimensions import DimensionEnvelope, PRODUCTION_DIMENSION_ENVELOPE
from .palette import (
    BG01,
    CANONICAL_PALETTE,
    CanonicalPalette,
    PALETTE,
    PaletteColor,
    PaletteContractError,
    load_palette,
)
from .production import (
    PRODUCTION_COLOR_MAX,
    PRODUCTION_COLOR_MIN,
    PRODUCTION_DIMENSION_MAX,
    PRODUCTION_DIMENSION_MIN,
    ProductionContractError,
    validate_production_dimensions,
    validate_production_height,
    validate_production_used_color_count,
    validate_production_width,
)

__all__ = [
    "actual_used_palette_ids",
    "BG01",
    "CANONICAL_PALETTE",
    "CanonicalPalette",
    "ColorUsageContractError",
    "count_used_colors",
    "CURRENT_DIMENSION_SCHEMA_VERSION",
    "Difficulty",
    "DimensionBand",
    "DimensionContractError",
    "DimensionEnvelope",
    "dimension_band",
    "is_legal_dimensions",
    "LEGACY_DIMENSION_SCHEMA_VERSION",
    "load_palette",
    "PaletteColor",
    "PALETTE",
    "PaletteContractError",
    "PRODUCTION_COLOR_MAX",
    "PRODUCTION_COLOR_MIN",
    "PRODUCTION_DIMENSION_MAX",
    "PRODUCTION_DIMENSION_MIN",
    "PRODUCTION_DIMENSION_ENVELOPE",
    "ProductionContractError",
    "parse_difficulty",
    "resolve_dimensions",
    "resolve_palette_subset",
    "select_dimensions",
    "SUPPORTED_DIMENSION_SCHEMA_VERSIONS",
    "select_palette_subset",
    "validate_dimensions",
    "validate_height",
    "validate_palette_subset",
    "validate_production_dimensions",
    "validate_production_height",
    "validate_production_used_color_count",
    "validate_production_width",
    "validate_used_color_count",
    "validate_width",
]
