"""Offline-only SCRUBBOTS Pixel Art Generator V1 foundation.

M00 intentionally exposes policy and local smoke utilities only. Generator
families and SCRUBBOTS contract modules belong to later milestones.
"""

from .offline import OfflinePolicyError, guarded_network_request, offline_runtime
from .local import deterministic_digest
from .contracts import (
    BG01,
    CANONICAL_PALETTE,
    ColorUsageContractError,
    Difficulty,
    DimensionContractError,
    PaletteContractError,
    actual_used_palette_ids,
    count_used_colors,
    resolve_dimensions,
    resolve_palette_subset,
    select_dimensions,
    select_palette_subset,
    validate_dimensions,
    validate_palette_subset,
    validate_used_color_count,
    PRODUCTION_COLOR_MAX,
    PRODUCTION_COLOR_MIN,
    PRODUCTION_DIMENSION_MAX,
    PRODUCTION_DIMENSION_MIN,
    ProductionContractError,
    validate_production_dimensions,
    validate_production_height,
    validate_production_used_color_count,
    validate_production_width,
)
from .core import (
    DeterministicRNG,
    FailureCode,
    GenerationFailureCode,
    GenerationRequest,
    GenerationResult,
    GeneratorMode,
    GeneratorOptions,
    PixelGenerator,
    RNG_ALGORITHM,
    ResultStatus,
)
from .generators.router import (
    AutoAttempt,
    AutoCandidate,
    GeneratorRouter,
    HybridCandidate,
    HybridGenerator,
    HybridStageMetadata,
    HybridStrategy,
    reproduce_hybrid,
)
from .quality import (
    DiversityReport,
    DuplicatePair,
    GridInput,
    QualityCode,
    QualityInputError,
    QualityPolicy,
    QualityReport,
    ReviewEntry,
    analyze_grid,
    compare_grids,
    diversity_report,
    evaluate_grid,
    exact_duplicate_groups,
    logical_grid_hash,
    write_review_pack,
)
from .output import (
    ARTWORK_SCHEMA,
    ARTWORK_SCHEMA_VERSION,
    ROW_MAJOR_INDEX_RULE,
    ArtworkArtifact,
    ArtworkContractError,
    BundleConflictError,
    DecodedPNG,
    ExportBundle,
    OutputContractError,
    PNGContractError,
    build_export_bundle,
    decode_logical_png,
    decode_png,
    encode_logical_png,
    encode_preview_png,
    export_candidate,
    export_result,
    logical_rgb_bytes,
    read_bundle,
    write_bundle,
)
from .studio_extensions import (
    StudioExtensionError,
    batch_import,
    candidate_inbox,
    compare_candidates,
    compare_revisions,
    cost_center,
    create_revision,
    discover_records,
    delete_preset,
    expand_preset,
    library_refresh,
    list_revisions,
    list_candidates,
    load_preset,
    load_revision,
    readiness_card,
    record_failure,
    record_owner_review,
    reproduce_capability,
    restore_session,
    retry_failure,
    run_pipeline,
    save_library_metadata,
    save_preset,
    save_session,
    similarity,
    validate_owner_source,
    verify_owner_source,
)
from .simulation_boundary import (
    AuthorityDescriptor,
    BOUNDARY_BRIDGE_VERSION,
    BoundaryCapability,
    BoundaryContractError,
    BoundaryDisposition,
    BridgeConfiguration,
    CANONICAL_CHECKOUT_ENVIRONMENT,
    CANONICAL_GAMEPLAY_REPOSITORY,
    CanonicalGameplayBridge,
    REQUIRED_CANONICAL_SOURCE_PATHS,
    SIMULATION_BOUNDARY_SCHEMA,
    SIMULATION_BOUNDARY_VERSION,
    SimulationRequest,
    SimulationResult,
)
from .compact_solver_state import (
    ACTIVE_BYTE,
    AUTHORITY_CONTRACT_SCHEMA,
    AUTHORITY_CONTRACT_VERSION,
    AUTHORITY_SCHEMA,
    AUTHORITY_VERSION,
    CANONICAL_PROOF_STATE_AUTHORITY_SHA,
    CANONICAL_PROOF_STATE_SOURCE_SHA256,
    CLEARED_BYTE,
    COMPACT_STATE_SCHEMA,
    COMPACT_STATE_VERSION,
    CompactSolverState,
    CompactStateContractError,
    LevelIdentity,
    OccupiedSlot,
    SolverStateAuthority,
    SupplyBatch,
    AuthorityVerification,
    AuthorityVerificationDisposition,
    AuthoritySourceVerification,
    verify_authority_checkout,
    verify_authority_source_contract,
)
from .legal_move_provider import (
    CANONICAL_PROVIDER_ID,
    CANONICAL_PROVIDER_VERSION,
    LEGAL_MOVE_KIND,
    LEGAL_MOVE_PROVIDER_SCHEMA,
    LEGAL_MOVE_PROVIDER_VERSION,
    CanonicalLegalMoveProvider,
    LegalMove,
    LegalMoveProvider,
    LegalMoveProviderError,
    LegalMoveQuery,
    LegalMoveResult,
    ProviderDisposition,
    ProviderEvidence,
)
from .baseline_search import (
    BASELINE_SEARCH_POLICY,
    BASELINE_SEARCH_SCHEMA,
    BASELINE_SEARCH_VERSION,
    BaselineSearchEngine,
    BaselineSearchPolicy,
    BaselineSearchResult,
    SearchContractError,
    SearchExecutionDisposition,
    SearchTransitionProvider,
    SearchVerdict,
    TerminalObservation,
    TerminalTruth,
    TransitionObservation,
)
from .visited_memoization import (
    CANONICAL_KEY_PROVIDER_ID,
    CANONICAL_KEY_PROVIDER_VERSION,
    CanonicalStateKeyProvider,
    DeterministicVisitedMemo,
    MemoDisposition,
    MemoObservation,
    MemoizationContractError,
    STATE_KEY_SCHEMA,
    STATE_KEY_VERSION,
    StateKeyDisposition,
    StateKeyEvidence,
    StateKeyResult,
    UnavailableCanonicalStateKeyProvider,
)
from .solver_evidence import (
    MAX_STATE_REFERENCES,
    SOLVER_EVIDENCE_SCHEMA,
    SOLVER_EVIDENCE_VERSION,
    EvidenceSearchEngine,
    SolverEvidenceReport,
    SolverMetrics,
)
from .search_policy import (
    BASELINE_SEARCH_POLICY as BASELINE_OPTIMIZATION_POLICY,
    NONE_PRUNING_V1,
    MoveOrderingPolicy,
    OrderingPolicy,
    PROVIDER_ORDER_V1,
    PruningPolicy,
    REVERSE_PROVIDER_ORDER_V1,
    REVERSE_SEARCH_POLICY,
    SEARCH_POLICY_SCHEMA,
    SEARCH_POLICY_VERSION,
    SearchOptimizationPolicy,
    SearchPolicy,
    SearchPolicyError,
)
from .solution_analysis import (
    ENTROPY_ANALYSIS_VERSION,
    EntropyDisposition,
    MOVE_SEQUENCE_EQUIVALENCE_V1,
    SOLUTION_ANALYSIS_SCHEMA,
    SOLUTION_ANALYSIS_VERSION,
    SolutionAnalysisBounds,
    SolutionAnalysisError,
    SolutionCountDisposition,
    SolutionCountEngine,
    SolutionCountResult,
)
from .solver_budget import (
    OPERATIONAL_TIMEOUT_POLICY_VERSION,
    SOLVER_BUDGET_SCHEMA,
    SOLVER_BUDGET_VERSION,
    SOLVER_OUTCOME_SCHEMA,
    SOLVER_OUTCOME_VERSION,
    BudgetExhaustionReason,
    BudgetedSolverResult,
    OperationalExecutionDisposition,
    OperationalSolverOutcome,
    OperationalTimeoutTelemetry,
    SolverBudgetError,
    SolverBudgetPolicy,
    SolverOutcomeDisposition,
    classify_search_result,
    classify_solution_count_result,
    wrap_operational_execution,
)
from .level_metrics import (
    AnalysisDisposition,
    DifficultyMetadata,
    LEVEL_METRICS_SCHEMA,
    LEVEL_METRICS_VERSION,
    LevelMetrics,
    LevelMetricsError,
    MetricId,
    MetricValues,
    METRICS_CONTRACT_SCHEMA,
    METRICS_CONTRACT_VERSION,
    MetricsContractIdentity,
    SolverEvidenceIdentity,
)
from .difficulty_analysis import (
    DEPENDENCY_DEPTH_SCHEMA,
    DEPENDENCY_DEPTH_VERSION,
    DependencyDepthResult,
    BAIT_DEADLOCK_SCHEMA,
    BAIT_DEADLOCK_VERSION,
    BaitDeadlockResult,
    SLOT_PRESSURE_SCHEMA,
    SLOT_PRESSURE_VERSION,
    SlotPressureResult,
    SlotSnapshot,
    populate_dependency_depth,
    populate_bait_deadlock,
    populate_search_complexity_metrics,
    populate_solution_depth_and_move_count,
    populate_slot_pressure,
    slot_pressure_from_snapshots,
    bait_deadlock_from_children,
    unavailable_slot_pressure_result,
    unavailable_dependency_result,
)
from .canonical_bridge import (
    CANONICAL_BRIDGE_RUNNER_VERSION,
    CANONICAL_BRIDGE_SCHEMA,
    CANONICAL_BRIDGE_VERSION,
    CanonicalBridgeConfiguration,
    CanonicalBridgeDisposition,
    CanonicalBridgeError,
    CanonicalBridgeRequest,
    CanonicalBridgeResponse,
    CanonicalHeadlessBridge,
)
from .reproduction import (
    REPRODUCTION_SCHEMA,
    REPRODUCTION_VERSION,
    ReplayDisposition,
    ReplayExecutionContext,
    ReplayObservation,
    ReplayResult,
    ReproductionBundle,
    ReproductionContractError,
    ReproductionManifest,
    ReproductionReplay,
)
from .semantic import (
    CELL_MAJORITY_POLICY_VERSION,
    CandidateStatus,
    ImageDescriptor,
    ImageInputDescriptor,
    ImageInputRole,
    OutputClass,
    ProviderResult,
    ProviderUnavailableError,
    SemanticCapabilities,
    SemanticCandidateError,
    SemanticContractError,
    SemanticGenerationRequest,
    SemanticGeneratorProvider,
    SemanticImageCandidate,
    SemanticImageInputDescriptor,
    SemanticNormalizationRequiredError,
    SemanticProviderError,
    SemanticProvenanceError,
    SemanticProviderResult,
    SemanticRequestError,
    SemanticOutputClass,
    SemanticProviderCapabilities,
    SemanticResult,
    SEMANTIC_RAW_RASTER_MAX_DIMENSION,
    DIFFICULTY_BUDGET_POLICY_VERSION,
    PRODUCTION_COLOR_ENVELOPE_POLICY_VERSION,
    LEVEL_ART_REPORT_SCHEMA,
    LEVEL_ART_REPORT_VERSION,
    LEVEL_ART_SCHEMA,
    LEVEL_ART_SCHEMA_VERSION,
    PALETTE_SNAP_POLICY_VERSION,
    LevelArtStatus,
    SemanticDecodeError,
    SemanticLevelArtArtifact,
    SemanticLevelArtCompiler,
    SemanticLevelArtError,
    SemanticLevelArtReport,
    SemanticLevelArtRequest,
    SemanticNormalizedArtifact,
    SemanticNormalizationError,
    SemanticNormalizationReport,
    SemanticNormalizationRequest,
    SemanticNormalizer,
    SemanticRawArtifact,
    SemanticSourceProvenance,
    cell_majority_rgba_grid,
    compile_level_art,
    compile_semantic_level_art,
    enforce_difficulty_color_budget,
    normalize_semantic_artifact,
    palette_snap_grid,
    SEMANTIC_QUALITY_ASSESSMENT_SCHEMA,
    SEMANTIC_QUALITY_ASSESSMENT_SCHEMA_VERSION,
    SEMANTIC_QUALITY_DIAGNOSTICS_POLICY_VERSION,
    SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA,
    SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA_VERSION,
    SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA,
    SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA_VERSION,
    RecognizabilityDisposition,
    SemanticQualityAssessment,
    SemanticQualityDiagnostics,
    SemanticQualityError,
    SemanticRecognizabilityReview,
    assess_semantic_quality,
    SEMANTIC_QUALITY_EVIDENCE_SCHEMA,
    SEMANTIC_QUALITY_EVIDENCE_SCHEMA_VERSION,
    SemanticQualityEvidenceRecord,
    export_semantic_quality_evidence,
    load_semantic_quality_evidence,
    require_semantic_recognizability_acceptance,
    SEMANTIC_GENERATION_INPUT_SCHEMA,
    SEMANTIC_GENERATION_PLAN_SCHEMA,
    SEMANTIC_GENERATION_PLAN_SCHEMA_VERSION,
    SEMANTIC_GENERATION_POLICY_VERSION,
    SEMANTIC_GENERATION_VARIANT_SCHEMA,
    SemanticGenerationPlanError,
    SemanticGenerationVariant,
    SemanticInputBinding,
    SemanticReferenceStylePlan,
    plan_reference_style_generation,
    BENCHMARK_CORPUS_VERSION, CORPUS_VERSION, MAX_PLAN_ATTEMPTS, PLAN_VERSION,
    QUALIFICATION_SCHEMA, QUALIFICATION_SCHEMA_VERSION, REVIEW_PACK_VERSION,
    BenchmarkCase, CostUsageRecord, MetadataBlindReviewItem, MetadataBlindReviewPack,
    NormalizationCompatibility, NormalizationEvidence, OwnerReviewDisposition,
    ProviderWorkflowSpec, QualificationAttemptRecord, QualificationEvidenceReference,
    QualificationLifecycle, QualificationPlan, QualificationPlanEntry, QualificationSummary,
    RawImportEvidence, build_metadata_blind_review_pack, build_qualification_plan,
    default_benchmark_corpus, default_evidence_references, default_provider_workflow_matrix,
    summarize_qualification,
    UnsupportedCapabilityError,
)

__all__ = [
    "OfflinePolicyError",
    "guarded_network_request",
    "offline_runtime",
    "deterministic_digest",
    "BG01",
    "CANONICAL_PALETTE",
    "ColorUsageContractError",
    "Difficulty",
    "DimensionContractError",
    "PaletteContractError",
    "actual_used_palette_ids",
    "count_used_colors",
    "resolve_dimensions",
    "resolve_palette_subset",
    "select_dimensions",
    "select_palette_subset",
    "validate_dimensions",
    "validate_palette_subset",
    "validate_used_color_count",
    "PRODUCTION_COLOR_MAX",
    "PRODUCTION_COLOR_MIN",
    "PRODUCTION_DIMENSION_MAX",
    "PRODUCTION_DIMENSION_MIN",
    "ProductionContractError",
    "validate_production_dimensions",
    "validate_production_height",
    "validate_production_used_color_count",
    "validate_production_width",
    "CELL_MAJORITY_POLICY_VERSION",
    "DeterministicRNG",
    "DIFFICULTY_BUDGET_POLICY_VERSION",
    "PRODUCTION_COLOR_ENVELOPE_POLICY_VERSION",
    "FailureCode",
    "GenerationFailureCode",
    "GenerationRequest",
    "GenerationResult",
    "GeneratorMode",
    "GeneratorOptions",
    "PixelGenerator",
    "RNG_ALGORITHM",
    "ResultStatus",
    "AutoAttempt",
    "AutoCandidate",
    "GeneratorRouter",
    "HybridCandidate",
    "HybridGenerator",
    "HybridStageMetadata",
    "HybridStrategy",
    "reproduce_hybrid",
    "DiversityReport",
    "DuplicatePair",
    "GridInput",
    "QualityCode",
    "QualityInputError",
    "QualityPolicy",
    "QualityReport",
    "ReviewEntry",
    "analyze_grid",
    "compare_grids",
    "diversity_report",
    "evaluate_grid",
    "exact_duplicate_groups",
    "logical_grid_hash",
    "write_review_pack",
    "ARTWORK_SCHEMA",
    "ARTWORK_SCHEMA_VERSION",
    "ROW_MAJOR_INDEX_RULE",
    "ArtworkArtifact",
    "ArtworkContractError",
    "BundleConflictError",
    "DecodedPNG",
    "ExportBundle",
    "OutputContractError",
    "PNGContractError",
    "build_export_bundle",
    "decode_logical_png",
    "decode_png",
    "encode_logical_png",
    "encode_preview_png",
    "export_candidate",
    "export_result",
    "logical_rgb_bytes",
    "read_bundle",
    "write_bundle",
    "CandidateStatus",
    "ImageDescriptor",
    "ImageInputDescriptor",
    "ImageInputRole",
    "OutputClass",
    "ProviderResult",
    "ProviderUnavailableError",
    "SemanticCapabilities",
    "SemanticCandidateError",
    "SemanticContractError",
    "SemanticGenerationRequest",
    "SemanticGeneratorProvider",
    "SemanticImageCandidate",
    "SemanticImageInputDescriptor",
    "SemanticNormalizationRequiredError",
    "SemanticOutputClass",
    "SemanticProviderCapabilities",
    "SemanticProviderError",
    "SemanticProvenanceError",
    "SemanticProviderResult",
    "SemanticRequestError",
    "SemanticResult",
    "SEMANTIC_RAW_RASTER_MAX_DIMENSION",
    "LEVEL_ART_REPORT_SCHEMA",
    "LEVEL_ART_REPORT_VERSION",
    "LEVEL_ART_SCHEMA",
    "LEVEL_ART_SCHEMA_VERSION",
    "PALETTE_SNAP_POLICY_VERSION",
    "LevelArtStatus",
    "SemanticDecodeError",
    "SemanticLevelArtArtifact",
    "SemanticLevelArtCompiler",
    "SemanticLevelArtError",
    "SemanticLevelArtReport",
    "SemanticLevelArtRequest",
    "SemanticNormalizedArtifact",
    "SemanticNormalizationError",
    "SemanticNormalizationReport",
    "SemanticNormalizationRequest",
    "SemanticNormalizer",
    "SemanticRawArtifact",
    "SemanticSourceProvenance",
    "cell_majority_rgba_grid",
    "compile_level_art",
    "compile_semantic_level_art",
    "enforce_difficulty_color_budget",
    "normalize_semantic_artifact",
    "palette_snap_grid",
    "SEMANTIC_QUALITY_ASSESSMENT_SCHEMA", "SEMANTIC_QUALITY_ASSESSMENT_SCHEMA_VERSION",
    "SEMANTIC_QUALITY_DIAGNOSTICS_POLICY_VERSION", "SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA",
    "SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA_VERSION", "SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA",
    "SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA_VERSION", "RecognizabilityDisposition",
    "SemanticQualityAssessment", "SemanticQualityDiagnostics", "SemanticQualityError",
    "SemanticRecognizabilityReview", "assess_semantic_quality",
    "SEMANTIC_QUALITY_EVIDENCE_SCHEMA", "SEMANTIC_QUALITY_EVIDENCE_SCHEMA_VERSION",
    "SemanticQualityEvidenceRecord", "export_semantic_quality_evidence",
    "load_semantic_quality_evidence", "require_semantic_recognizability_acceptance",
    "SEMANTIC_GENERATION_INPUT_SCHEMA", "SEMANTIC_GENERATION_PLAN_SCHEMA",
    "SEMANTIC_GENERATION_PLAN_SCHEMA_VERSION", "SEMANTIC_GENERATION_POLICY_VERSION",
    "SEMANTIC_GENERATION_VARIANT_SCHEMA", "SemanticGenerationPlanError",
    "SemanticGenerationVariant", "SemanticInputBinding", "SemanticReferenceStylePlan",
    "plan_reference_style_generation",
    "BENCHMARK_CORPUS_VERSION", "CORPUS_VERSION", "MAX_PLAN_ATTEMPTS", "PLAN_VERSION",
    "QUALIFICATION_SCHEMA", "QUALIFICATION_SCHEMA_VERSION", "REVIEW_PACK_VERSION",
    "BenchmarkCase", "CostUsageRecord", "MetadataBlindReviewItem", "MetadataBlindReviewPack",
    "NormalizationCompatibility", "NormalizationEvidence", "OwnerReviewDisposition",
    "ProviderWorkflowSpec", "QualificationAttemptRecord", "QualificationEvidenceReference",
    "QualificationLifecycle", "QualificationPlan", "QualificationPlanEntry", "QualificationSummary",
    "RawImportEvidence", "build_metadata_blind_review_pack", "build_qualification_plan",
    "default_benchmark_corpus", "default_evidence_references", "default_provider_workflow_matrix",
    "summarize_qualification",
    "UnsupportedCapabilityError",
    "StudioExtensionError", "batch_import", "candidate_inbox", "compare_candidates", "compare_revisions", "cost_center", "create_revision", "delete_preset", "discover_records", "expand_preset", "library_refresh", "list_candidates", "list_revisions", "load_preset", "load_revision", "readiness_card", "record_failure", "record_owner_review", "reproduce_capability", "restore_session", "retry_failure", "run_pipeline", "save_library_metadata", "save_preset", "save_session", "similarity", "validate_owner_source", "verify_owner_source",
    "AuthorityDescriptor", "BOUNDARY_BRIDGE_VERSION", "BoundaryCapability", "BoundaryContractError", "BoundaryDisposition", "BridgeConfiguration", "CANONICAL_CHECKOUT_ENVIRONMENT", "CANONICAL_GAMEPLAY_REPOSITORY", "CanonicalGameplayBridge", "REQUIRED_CANONICAL_SOURCE_PATHS", "SIMULATION_BOUNDARY_SCHEMA", "SIMULATION_BOUNDARY_VERSION", "SimulationRequest", "SimulationResult",
    "ACTIVE_BYTE", "AUTHORITY_CONTRACT_SCHEMA", "AUTHORITY_CONTRACT_VERSION", "AUTHORITY_SCHEMA", "AUTHORITY_VERSION", "CANONICAL_PROOF_STATE_AUTHORITY_SHA", "CANONICAL_PROOF_STATE_SOURCE_SHA256", "CLEARED_BYTE", "COMPACT_STATE_SCHEMA", "COMPACT_STATE_VERSION", "CompactSolverState", "CompactStateContractError", "LevelIdentity", "OccupiedSlot", "SolverStateAuthority", "SupplyBatch", "AuthorityVerification", "AuthorityVerificationDisposition", "AuthoritySourceVerification", "verify_authority_checkout", "verify_authority_source_contract",
    "CANONICAL_PROVIDER_ID", "CANONICAL_PROVIDER_VERSION", "LEGAL_MOVE_KIND", "LEGAL_MOVE_PROVIDER_SCHEMA", "LEGAL_MOVE_PROVIDER_VERSION", "CanonicalLegalMoveProvider", "LegalMove", "LegalMoveProvider", "LegalMoveProviderError", "LegalMoveQuery", "LegalMoveResult", "ProviderDisposition", "ProviderEvidence",
    "BASELINE_SEARCH_POLICY", "BASELINE_SEARCH_SCHEMA", "BASELINE_SEARCH_VERSION", "BaselineSearchEngine", "BaselineSearchPolicy", "BaselineSearchResult", "SearchContractError", "SearchExecutionDisposition", "SearchTransitionProvider", "SearchVerdict", "TerminalObservation", "TerminalTruth", "TransitionObservation",
    "CANONICAL_KEY_PROVIDER_ID", "CANONICAL_KEY_PROVIDER_VERSION", "CanonicalStateKeyProvider", "DeterministicVisitedMemo", "MemoDisposition", "MemoObservation", "MemoizationContractError", "STATE_KEY_SCHEMA", "STATE_KEY_VERSION", "StateKeyDisposition", "StateKeyEvidence", "StateKeyResult", "UnavailableCanonicalStateKeyProvider",
    "MAX_STATE_REFERENCES", "SOLVER_EVIDENCE_SCHEMA", "SOLVER_EVIDENCE_VERSION", "EvidenceSearchEngine", "SolverEvidenceReport", "SolverMetrics",
    "BASELINE_OPTIMIZATION_POLICY", "NONE_PRUNING_V1", "MoveOrderingPolicy", "OrderingPolicy", "PROVIDER_ORDER_V1", "PruningPolicy", "REVERSE_PROVIDER_ORDER_V1", "REVERSE_SEARCH_POLICY", "SEARCH_POLICY_SCHEMA", "SEARCH_POLICY_VERSION", "SearchOptimizationPolicy", "SearchPolicy", "SearchPolicyError",
    "ENTROPY_ANALYSIS_VERSION", "EntropyDisposition", "MOVE_SEQUENCE_EQUIVALENCE_V1", "SOLUTION_ANALYSIS_SCHEMA", "SOLUTION_ANALYSIS_VERSION", "SolutionAnalysisBounds", "SolutionAnalysisError", "SolutionCountDisposition", "SolutionCountEngine", "SolutionCountResult",
    "OPERATIONAL_TIMEOUT_POLICY_VERSION", "SOLVER_BUDGET_SCHEMA", "SOLVER_BUDGET_VERSION", "SOLVER_OUTCOME_SCHEMA", "SOLVER_OUTCOME_VERSION", "BudgetExhaustionReason", "BudgetedSolverResult", "OperationalExecutionDisposition", "OperationalSolverOutcome", "OperationalTimeoutTelemetry", "SolverBudgetError", "SolverBudgetPolicy", "SolverOutcomeDisposition", "classify_search_result", "classify_solution_count_result", "wrap_operational_execution",
    "AnalysisDisposition", "DifficultyMetadata", "LEVEL_METRICS_SCHEMA", "LEVEL_METRICS_VERSION", "LevelMetrics", "LevelMetricsError", "MetricId", "MetricValues", "METRICS_CONTRACT_SCHEMA", "METRICS_CONTRACT_VERSION", "MetricsContractIdentity", "SolverEvidenceIdentity", "DEPENDENCY_DEPTH_SCHEMA", "DEPENDENCY_DEPTH_VERSION", "DependencyDepthResult", "BAIT_DEADLOCK_SCHEMA", "BAIT_DEADLOCK_VERSION", "BaitDeadlockResult", "SLOT_PRESSURE_SCHEMA", "SLOT_PRESSURE_VERSION", "SlotPressureResult", "SlotSnapshot", "populate_dependency_depth", "populate_bait_deadlock", "populate_search_complexity_metrics", "populate_solution_depth_and_move_count", "populate_slot_pressure", "slot_pressure_from_snapshots", "bait_deadlock_from_children", "unavailable_slot_pressure_result", "unavailable_dependency_result",
    "CANONICAL_BRIDGE_RUNNER_VERSION", "CANONICAL_BRIDGE_SCHEMA", "CANONICAL_BRIDGE_VERSION", "CanonicalBridgeConfiguration", "CanonicalBridgeDisposition", "CanonicalBridgeError", "CanonicalBridgeRequest", "CanonicalBridgeResponse", "CanonicalHeadlessBridge",
    "REPRODUCTION_SCHEMA", "REPRODUCTION_VERSION", "ReplayDisposition", "ReplayExecutionContext", "ReplayObservation", "ReplayResult", "ReproductionBundle", "ReproductionContractError", "ReproductionManifest", "ReproductionReplay",
]

__version__ = "0.1.0"
OFFLINE_ONLY = True
