"""Offline-only SCRUBBOTS Pixel Art Generator V1 foundation.

M00 intentionally exposes policy and local smoke utilities only. Generator
families and SCRUBBOTS contract modules belong to later milestones.
"""

from .offline import OfflinePolicyError, guarded_network_request, offline_runtime
from .local import deterministic_digest
from .contracts import (
    BG01,
    CANONICAL_PALETTE,
    ColorUsageContractError,
    Difficulty,
    DimensionContractError,
    PaletteContractError,
    actual_used_palette_ids,
    count_used_colors,
    resolve_dimensions,
    resolve_palette_subset,
    select_dimensions,
    select_palette_subset,
    validate_dimensions,
    validate_palette_subset,
    validate_used_color_count,
    PRODUCTION_COLOR_MAX,
    PRODUCTION_COLOR_MIN,
    PRODUCTION_DIMENSION_MAX,
    PRODUCTION_DIMENSION_MIN,
    ProductionContractError,
    validate_production_dimensions,
    validate_production_height,
    validate_production_used_color_count,
    validate_production_width,
)
from .core import (
    DeterministicRNG,
    FailureCode,
    GenerationFailureCode,
    GenerationRequest,
    GenerationResult,
    GeneratorMode,
    GeneratorOptions,
    PixelGenerator,
    RNG_ALGORITHM,
    ResultStatus,
)
from .generators.router import (
    AutoAttempt,
    AutoCandidate,
    GeneratorRouter,
    HybridCandidate,
    HybridGenerator,
    HybridStageMetadata,
    HybridStrategy,
    reproduce_hybrid,
)
from .quality import (
    DiversityReport,
    DuplicatePair,
    GridInput,
    QualityCode,
    QualityInputError,
    QualityPolicy,
    QualityReport,
    ReviewEntry,
    analyze_grid,
    compare_grids,
    diversity_report,
    evaluate_grid,
    exact_duplicate_groups,
    logical_grid_hash,
    write_review_pack,
)
from .output import (
    ARTWORK_SCHEMA,
    ARTWORK_SCHEMA_VERSION,
    ROW_MAJOR_INDEX_RULE,
    ArtworkArtifact,
    ArtworkContractError,
    BundleConflictError,
    DecodedPNG,
    ExportBundle,
    OutputContractError,
    PNGContractError,
    build_export_bundle,
    decode_logical_png,
    decode_png,
    encode_logical_png,
    encode_preview_png,
    export_candidate,
    export_result,
    logical_rgb_bytes,
    read_bundle,
    write_bundle,
)
from .semantic import (
    CELL_MAJORITY_POLICY_VERSION,
    CandidateStatus,
    ImageDescriptor,
    ImageInputDescriptor,
    ImageInputRole,
    OutputClass,
    ProviderResult,
    ProviderUnavailableError,
    SemanticCapabilities,
    SemanticCandidateError,
    SemanticContractError,
    SemanticGenerationRequest,
    SemanticGeneratorProvider,
    SemanticImageCandidate,
    SemanticImageInputDescriptor,
    SemanticNormalizationRequiredError,
    SemanticProviderError,
    SemanticProvenanceError,
    SemanticProviderResult,
    SemanticRequestError,
    SemanticOutputClass,
    SemanticProviderCapabilities,
    SemanticResult,
    SEMANTIC_RAW_RASTER_MAX_DIMENSION,
    DIFFICULTY_BUDGET_POLICY_VERSION,
    PRODUCTION_COLOR_ENVELOPE_POLICY_VERSION,
    LEVEL_ART_REPORT_SCHEMA,
    LEVEL_ART_REPORT_VERSION,
    LEVEL_ART_SCHEMA,
    LEVEL_ART_SCHEMA_VERSION,
    PALETTE_SNAP_POLICY_VERSION,
    LevelArtStatus,
    SemanticDecodeError,
    SemanticLevelArtArtifact,
    SemanticLevelArtCompiler,
    SemanticLevelArtError,
    SemanticLevelArtReport,
    SemanticLevelArtRequest,
    SemanticNormalizedArtifact,
    SemanticNormalizationError,
    SemanticNormalizationReport,
    SemanticNormalizationRequest,
    SemanticNormalizer,
    SemanticRawArtifact,
    SemanticSourceProvenance,
    cell_majority_rgba_grid,
    compile_level_art,
    compile_semantic_level_art,
    enforce_difficulty_color_budget,
    normalize_semantic_artifact,
    palette_snap_grid,
    SEMANTIC_QUALITY_ASSESSMENT_SCHEMA,
    SEMANTIC_QUALITY_ASSESSMENT_SCHEMA_VERSION,
    SEMANTIC_QUALITY_DIAGNOSTICS_POLICY_VERSION,
    SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA,
    SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA_VERSION,
    SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA,
    SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA_VERSION,
    RecognizabilityDisposition,
    SemanticQualityAssessment,
    SemanticQualityDiagnostics,
    SemanticQualityError,
    SemanticRecognizabilityReview,
    assess_semantic_quality,
    SEMANTIC_QUALITY_EVIDENCE_SCHEMA,
    SEMANTIC_QUALITY_EVIDENCE_SCHEMA_VERSION,
    SemanticQualityEvidenceRecord,
    export_semantic_quality_evidence,
    load_semantic_quality_evidence,
    require_semantic_recognizability_acceptance,
    SEMANTIC_GENERATION_INPUT_SCHEMA,
    SEMANTIC_GENERATION_PLAN_SCHEMA,
    SEMANTIC_GENERATION_PLAN_SCHEMA_VERSION,
    SEMANTIC_GENERATION_POLICY_VERSION,
    SEMANTIC_GENERATION_VARIANT_SCHEMA,
    SemanticGenerationPlanError,
    SemanticGenerationVariant,
    SemanticInputBinding,
    SemanticReferenceStylePlan,
    plan_reference_style_generation,
    BENCHMARK_CORPUS_VERSION, CORPUS_VERSION, MAX_PLAN_ATTEMPTS, PLAN_VERSION,
    QUALIFICATION_SCHEMA, QUALIFICATION_SCHEMA_VERSION, REVIEW_PACK_VERSION,
    BenchmarkCase, CostUsageRecord, MetadataBlindReviewItem, MetadataBlindReviewPack,
    NormalizationCompatibility, NormalizationEvidence, OwnerReviewDisposition,
    ProviderWorkflowSpec, QualificationAttemptRecord, QualificationEvidenceReference,
    QualificationLifecycle, QualificationPlan, QualificationPlanEntry, QualificationSummary,
    RawImportEvidence, build_metadata_blind_review_pack, build_qualification_plan,
    default_benchmark_corpus, default_evidence_references, default_provider_workflow_matrix,
    summarize_qualification,
    UnsupportedCapabilityError,
)

__all__ = [
    "OfflinePolicyError",
    "guarded_network_request",
    "offline_runtime",
    "deterministic_digest",
    "BG01",
    "CANONICAL_PALETTE",
    "ColorUsageContractError",
    "Difficulty",
    "DimensionContractError",
    "PaletteContractError",
    "actual_used_palette_ids",
    "count_used_colors",
    "resolve_dimensions",
    "resolve_palette_subset",
    "select_dimensions",
    "select_palette_subset",
    "validate_dimensions",
    "validate_palette_subset",
    "validate_used_color_count",
    "PRODUCTION_COLOR_MAX",
    "PRODUCTION_COLOR_MIN",
    "PRODUCTION_DIMENSION_MAX",
    "PRODUCTION_DIMENSION_MIN",
    "ProductionContractError",
    "validate_production_dimensions",
    "validate_production_height",
    "validate_production_used_color_count",
    "validate_production_width",
    "CELL_MAJORITY_POLICY_VERSION",
    "DeterministicRNG",
    "DIFFICULTY_BUDGET_POLICY_VERSION",
    "PRODUCTION_COLOR_ENVELOPE_POLICY_VERSION",
    "FailureCode",
    "GenerationFailureCode",
    "GenerationRequest",
    "GenerationResult",
    "GeneratorMode",
    "GeneratorOptions",
    "PixelGenerator",
    "RNG_ALGORITHM",
    "ResultStatus",
    "AutoAttempt",
    "AutoCandidate",
    "GeneratorRouter",
    "HybridCandidate",
    "HybridGenerator",
    "HybridStageMetadata",
    "HybridStrategy",
    "reproduce_hybrid",
    "DiversityReport",
    "DuplicatePair",
    "GridInput",
    "QualityCode",
    "QualityInputError",
    "QualityPolicy",
    "QualityReport",
    "ReviewEntry",
    "analyze_grid",
    "compare_grids",
    "diversity_report",
    "evaluate_grid",
    "exact_duplicate_groups",
    "logical_grid_hash",
    "write_review_pack",
    "ARTWORK_SCHEMA",
    "ARTWORK_SCHEMA_VERSION",
    "ROW_MAJOR_INDEX_RULE",
    "ArtworkArtifact",
    "ArtworkContractError",
    "BundleConflictError",
    "DecodedPNG",
    "ExportBundle",
    "OutputContractError",
    "PNGContractError",
    "build_export_bundle",
    "decode_logical_png",
    "decode_png",
    "encode_logical_png",
    "encode_preview_png",
    "export_candidate",
    "export_result",
    "logical_rgb_bytes",
    "read_bundle",
    "write_bundle",
    "CandidateStatus",
    "ImageDescriptor",
    "ImageInputDescriptor",
    "ImageInputRole",
    "OutputClass",
    "ProviderResult",
    "ProviderUnavailableError",
    "SemanticCapabilities",
    "SemanticCandidateError",
    "SemanticContractError",
    "SemanticGenerationRequest",
    "SemanticGeneratorProvider",
    "SemanticImageCandidate",
    "SemanticImageInputDescriptor",
    "SemanticNormalizationRequiredError",
    "SemanticOutputClass",
    "SemanticProviderCapabilities",
    "SemanticProviderError",
    "SemanticProvenanceError",
    "SemanticProviderResult",
    "SemanticRequestError",
    "SemanticResult",
    "SEMANTIC_RAW_RASTER_MAX_DIMENSION",
    "LEVEL_ART_REPORT_SCHEMA",
    "LEVEL_ART_REPORT_VERSION",
    "LEVEL_ART_SCHEMA",
    "LEVEL_ART_SCHEMA_VERSION",
    "PALETTE_SNAP_POLICY_VERSION",
    "LevelArtStatus",
    "SemanticDecodeError",
    "SemanticLevelArtArtifact",
    "SemanticLevelArtCompiler",
    "SemanticLevelArtError",
    "SemanticLevelArtReport",
    "SemanticLevelArtRequest",
    "SemanticNormalizedArtifact",
    "SemanticNormalizationError",
    "SemanticNormalizationReport",
    "SemanticNormalizationRequest",
    "SemanticNormalizer",
    "SemanticRawArtifact",
    "SemanticSourceProvenance",
    "cell_majority_rgba_grid",
    "compile_level_art",
    "compile_semantic_level_art",
    "enforce_difficulty_color_budget",
    "normalize_semantic_artifact",
    "palette_snap_grid",
    "SEMANTIC_QUALITY_ASSESSMENT_SCHEMA", "SEMANTIC_QUALITY_ASSESSMENT_SCHEMA_VERSION",
    "SEMANTIC_QUALITY_DIAGNOSTICS_POLICY_VERSION", "SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA",
    "SEMANTIC_QUALITY_DIAGNOSTICS_SCHEMA_VERSION", "SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA",
    "SEMANTIC_RECOGNIZABILITY_REVIEW_SCHEMA_VERSION", "RecognizabilityDisposition",
    "SemanticQualityAssessment", "SemanticQualityDiagnostics", "SemanticQualityError",
    "SemanticRecognizabilityReview", "assess_semantic_quality",
    "SEMANTIC_QUALITY_EVIDENCE_SCHEMA", "SEMANTIC_QUALITY_EVIDENCE_SCHEMA_VERSION",
    "SemanticQualityEvidenceRecord", "export_semantic_quality_evidence",
    "load_semantic_quality_evidence", "require_semantic_recognizability_acceptance",
    "SEMANTIC_GENERATION_INPUT_SCHEMA", "SEMANTIC_GENERATION_PLAN_SCHEMA",
    "SEMANTIC_GENERATION_PLAN_SCHEMA_VERSION", "SEMANTIC_GENERATION_POLICY_VERSION",
    "SEMANTIC_GENERATION_VARIANT_SCHEMA", "SemanticGenerationPlanError",
    "SemanticGenerationVariant", "SemanticInputBinding", "SemanticReferenceStylePlan",
    "plan_reference_style_generation",
    "BENCHMARK_CORPUS_VERSION", "CORPUS_VERSION", "MAX_PLAN_ATTEMPTS", "PLAN_VERSION",
    "QUALIFICATION_SCHEMA", "QUALIFICATION_SCHEMA_VERSION", "REVIEW_PACK_VERSION",
    "BenchmarkCase", "CostUsageRecord", "MetadataBlindReviewItem", "MetadataBlindReviewPack",
    "NormalizationCompatibility", "NormalizationEvidence", "OwnerReviewDisposition",
    "ProviderWorkflowSpec", "QualificationAttemptRecord", "QualificationEvidenceReference",
    "QualificationLifecycle", "QualificationPlan", "QualificationPlanEntry", "QualificationSummary",
    "RawImportEvidence", "build_metadata_blind_review_pack", "build_qualification_plan",
    "default_benchmark_corpus", "default_evidence_references", "default_provider_workflow_matrix",
    "summarize_qualification",
    "UnsupportedCapabilityError",
]

__version__ = "0.1.0"
OFFLINE_ONLY = True
